import { daily } from "./fen-auto.js"

const uzay = [
  "Teleskop, çıplak gözün seçemediği cismi büyütür",
  "Uydu, Dünya’nın çevresinde dolanır ve veri gönderir",
  "İnsansız araç, insanı riske atmadan ölçüm yapar",
  "Işık yılı, ışığın bir yılda aldığı yoldur, zaman birimi değildir",
  "Roket, aracı yerçekiminden kurtarmak için itme üretir",
  "Uzay istasyonunda deney, yerçekiminin az hissedildiği ortamda yapılır",
  "Türkiye’nin uyduları iletişim ve gözlem için kullanılır",
  "Astronot kıyafeti basınç ve oksijen sağlar",
  "Güneş sisteminin dışına çıkan araçlar da Güneş’ten enerji taşıyabilir",
  "Göktaşı atmosfere girince ısınıp kayan yıldız gibi görünebilir",
  "Samanyolu, Güneş’in de içinde olduğu gökadadır",
  "Yıldızın rengi sıcaklığı hakkında ipucu verir",
  "Gezegen, yıldızın çevresinde dolanır",
  "Ay tutulması uzay aracı gerektirmez, Dünya’nın gölgesidir",
  "Uzay boşluğunda ses, tanecik olmadığı için iletilmez",
  "Güneş rüzgârı, Güneş’ten savrulan yüklü parçacıklardır",
  "Yörünge, cismin sürekli düşer gibi dolandığı yoldur",
  "Fırlatma penceresi, uygun zamandır, pencere camı değildir",
  "Uzay çöpü, işi bitmiş araç parçalarının çarpışma riskidir",
  "Bilimsel veri, tek fotoğrafla değil tekrarlanan ölçümle güçlenir",
]
const isEnerji = [
  "Bir cismi kuvvetle yer değiştirmek iş yapmaktır",
  "Kuvvet varken yol yoksa iş yoktur",
  "Yol kuvvete dikse o kuvvet iş yapmamış sayılır",
  "İş, kuvvet çarpı yoldur",
  "Enerji, iş yapabilme yeteneğidir",
  "Kinetik enerji hareketle ilgilidir",
  "Potansiyel enerji konumla birikebilir",
  "Yüksekteki suyun enerjisi aşağı düşünce harekete dönebilir",
  "Sürtünme, mekanik enerjinin bir kısmını ısıya çevirir",
  "Enerji yok olmaz, biçim değiştirir",
  "Besin, kimyasal enerji taşır",
  "Kas, kimyasal enerjiyi harekete çevirir",
  "Lamba, elektrik enerjisini ışığa çevirir",
  "Hoparlör, elektrik enerjisini sese çevirir",
  "Güneş pili ışığı elektriğe çevirir",
  "Pil, kimyasal enerjiyi elektrik enerjisine çevirir",
  "Sürtünen eller ısı üretir",
  "Yokuş inen bisiklet potansiyeli kinetiğe çevirir",
  "İş yapılmadan enerji aktarımı da düşünülemez",
]
const donusum = [
  "Tost makinesi elektriği ısıya çevirir",
  "Bisiklet dinamosu hareketi elektriğe çevirir",
  "Besin hücrede harekete dönüşür",
  "Rüzgâr türbini hareketi elektriğe çevirir",
  "Her dönüşümde bir kısım enerji ısıya dağılabilir",
]
const sindirim = [
  "Ağızda diş besini parçalar, tükürük nişastaya başlar",
  "Yemek borusu besini mideye taşır",
  "Midede asit ve enzim protein üzerinde çalışır",
  "İnce bağırsakta sindirim tamamlanır ve emilim olur",
  "Kalın bağırsak suyu geri emer",
  "Karaciğer safra üretir",
  "Pankreas enzimlerini ince bağırsağa gönderir",
  "Lifli besin bağırsağın çalışmasına yardım eder",
  "Aşırı şeker diş ve denge için risk oluşturur",
  "İyi çiğnemek mideye giden parçayı küçültür",
]
const dolasim = [
  "Kalp kanı damarlara pompalar",
  "Atardamar kanı kalpten uzaklaştırır",
  "Toplardamar kanı kalbe getirir",
  "Kılcal damar hücreyle alışverişin olduğu yerdir",
  "Alyuvar oksijen taşır",
  "Akyuvar hastalık etkenine karşı çalışır",
  "Trombosit kanamanın durmasına yardım eder",
  "Sigara damar sağlığını bozar",
  "Düzenli hareket kalbi güçlendirebilir",
  "Nabız, kalbin bir dakikadaki atışıdır",
]
const solunum = [
  "Burun havayı ısıtır ve süzer",
  "Soluk borusu havayı akciğere iletir",
  "Akciğerde oksijen kana, karbondioksit havaya geçer",
  "Diyafram kasılınca göğüs genişler ve hava girer",
  "Hücre solunumu besinden enerji çıkarır",
  "Sigara dumanı alveolleri zedeler",
  "Egzersiz soluk sayısını artırır",
  "Solunum ile fotosentez aynı işlem değildir",
  "Karbonmonoksit solunumu zehirleyebilir",
]
const bosaltim = [
  "Böbrek kanı süzerek idrar oluşturur",
  "İdrar kesesi idrarı bir süre depolar",
  "Deri terleyerek su ve tuz atabilir",
  "Akciğer karbondioksiti dışarı verir",
  "Su içmek böbreğin süzmesine yardım eder",
  "Aşırı tuz tansiyonu zorlayabilir",
  "Boşaltım, sindirim artığı ile aynı şey değildir",
  "Böbrek yetmezliğinde süzme bozulur",
  "Ter, vücut sıcaklığının düşmesine de yardım eder",
  "İdrarın rengi su az içilince koyulaşabilir",
]
const kirilma = [
  "Işık sudan havaya geçerken yön değiştirebilir",
  "Bardaktaki kaşık kırıkmış gibi görünür",
  "Kırılma, hızın ortam değiştirmesinden olur",
  "Gelme açısı büyüyünce kırılma açısı da değişir",
  "Tam yansıma, ışığın diğer ortama geçemeyip döndüğü sınırdır",
  "Serap, sıcak havada kırılmanın yarattığı görüntüdür",
  "Gözlük camı ışığı kırarak odaklar",
  "Havuz dibi olduğundan yakın görünebilir",
  "Kırılma yansıma değildir, ışık ikinci ortama geçer",
  "Normal, yüzeye dik çizilen referans doğrudur",
  "Az yoğun ortamdan çok yoğuna geçişte ışık normale yaklaşabilir",
  "Balıkçı zıpkını, görünen yere değil hesabın gösterdiği yere uzatır",
  "Elyaf kabloda ışık tam yansımayla ilerleyebilir",
  "Bulanık su kırılmayı da görüntüyü de bozar",
  "Kırılma açısı, kırılan ışın ile normal arasındaki açıdır",
]
const mercek = [
  "İnce kenarlı mercek ışığı toplayabilir",
  "Kalın kenarlı mercek ışığı dağıtabilir",
  "Yakını göremeyen kişi ince kenarlı mercek kullanabilir",
  "Uzağı göremeyen kişi kalın kenarlı mercek kullanabilir",
  "Büyüteç ince kenarlı bir mercektir",
  "Mercek kirlenirse görüntü bulanıklaşır",
  "Odak, toplanan ışınların buluştuğu noktadır",
  "Göz merceği ince kenarlı gibi çalışır",
  "Yanlış mercek baş ağrısı yapabilir",
  "Mercek, aynadan farklı olarak ışığı geçirerek kırar",
]
const atom = [
  "Atom, maddenin kimyasal özelliğini taşıyan küçük birimidir",
  "Element, tek cins atomdan oluşur",
  "Molekül, atomların bağlanmasıyla oluşabilir",
  "Oksijen gazı iki oksijen atomundan oluşan moleküldür",
  "Atom gözle değil modelle anlatılır",
]
const saf = [
  "Altın bir elementtir",
  "Su bir bileşiktir, hidrojen ve oksijenden oluşur",
  "Bileşik, elementlerine ayrılabilir ama element daha yalındır",
  "Erime noktası saf maddeler için ayırt edici olabilir",
  "Kaynama noktası da ayırt edici olabilir",
  "Yoğunluk saf maddeyi tanımaya yardım eder",
  "Tuzlu su saf madde değildir, karışımdır",
  "Demir elementi mıknatıs çeker",
  "Helyum tek cins atomdan oluşan bir gazdır",
  "Karbon elementi elmas ve grafitte farklı dizilir",
  "Bileşiğin özelliği, kendisini oluşturan elementlerden farklıdır",
  "Saf suyun iletkenliği tuzlu sudan düşüktür",
  "Ayırt edici özellik miktara göre değişmez",
  "Kütle ayırt edici değildir, miktarla artar",
  "Hacim de miktarla değişir",
  "Şekerli su homojen görünebilir ama saf değildir",
  "Element sembolle, bileşik formülle yazılabilir",
  "Ayrışan su hidrojen ve oksijen verir",
  "Saf madde tek cins tanecik düzenidir",
  "Karışım fiziksel yolla bileşenlerine ayrılabilir",
]
const karisim = [
  "Şekerli su homojendir, her yeri aynı görünür",
  "Kum-su heterojendir, taneler seçilir",
  "Derişim, belirli miktar çözeltideki çözünen orandır",
  "Seyreltik çözeltide çözünen azdır",
  "Derişik çay daha koyu görünür",
  "Çözelti bir karışımdır, bileşik değildir",
  "Su miktarı artarsa derişim düşer",
  "Aynı miktar tuz, az suda daha derişik olur",
  "Homojen karışımda sınır görünmez",
]
const ayirma = [
  "Talaş-kum karışımı suda yüzdürülerek ayrılabilir",
  "Tuzlu su buharlaştırılarak tuz bırakır",
  "Mıknatıs demiri kumdan ayırır",
  "Süzme, çözünmemiş katıyı sıvıdan tutar",
  "Yöntem, karışımın özelliğine göre seçilir",
]
const yukle = [
  "Plastik tarak saça sürtününce kâğıdı çeker",
  "Aynı cins yükler birbirini iter",
  "Zıt yükler birbirini çeker",
  "Nötr cisim, yüklü cisme yaklaşınca çekilebilir",
  "Dokunarak yüklenme, yükün geçmesidir",
  "Etki ile yüklenme, cismin içinde yüklerin ayrılmasıdır",
  "Topraklama, fazla yükün iletkenle uzaklaşmasıdır",
  "Kuru havada sürtünme elektriği daha belirgindir",
  "Yıldırımsavar, yükü güvenli yoldan toprağa iletir",
  "Metal iletken olduğu için yükü taşır",
  "Plastik yalıtkan olduğu için yükü üzerinde tutabilir",
  "Elektriklenme, yeni yük yaratmak değil yükü ayırmaktır",
]
const surdur = [
  "Güneş paneli yenilenebilir kaynaktan elektrik üretir",
  "Rüzgâr türbini yakıt yakmaz",
  "Kömür tükendiğinde yerine kolay konmaz",
  "Besin zincirinde enerji bir halkadan ötekine azalabilir",
  "Üretici, ışığı besine çevirir",
  "Tüketici hazır besin kullanır",
  "Ayrıştırıcı artığı toprağa döndürür",
  "Enerji tasarrufu kaynak ömrünü uzatır",
  "İsraf edilen ekmek, tarla ve su israfıdır",
  "LED lamba akkor lambadan az enerji harcayabilir",
  "Yalıtımlı ev ısı kaybını azaltır",
  "Bisiklet kısa yolda yakıt tüketmez",
  "Geri dönüşüm maden çıkarmayı azaltabilir",
  "Yenilenebilir kaynak da doğaya zarar vermeden kurulmalıdır",
  "Sürdürülebilir yaşam, tüketimi ihtiyaca yaklaştırır",
]
const yil7 = [
  "İş ile enerjiyi aynı sayı sanmak",
  "İnce kenarlı merceği dağıtıcı sanmak",
  "Tuzlu suyu element saymak",
  "Kırılmayı yansıma sanmak",
  "Yenilenebilir kaynağı tükenmez diye sınırsız zarar saymak",
]
const mevsim = [
  "21 Haziran’da Kuzey yarım küre yaz gündönümündedir",
  "21 Aralık’ta Kuzey yarım kürede kış başlar",
  "Ekinoks tarihlerinde gece ve gündüz süreleri eşitlenir",
  "Eksen eğik olmasaydı yıl boyu aynı ışık açısı sürerdi",
  "Mevsim, Güneş’e uzaklığın azalıp artması değildir",
  "Yazın Güneş ışınları daha dik gelir",
  "Kışın aynı enerji daha geniş alana yayıldığı için ısıtma azalır",
  "Hava, bir yerin kısa süreli durumudur",
  "İklim, uzun yılların ortalama düzenidir",
  "Bir günün yağmuru iklim değişikliği kanıtı sayılmaz",
  "Kutuplara yakın yerde mevsim farkı ışık süresiyle de hissedilir",
  "Ekvator çevresinde ışık açısı yıl boyu daha dik kalabilir",
  "Güney yarım kürede mevsimler Kuzey’in tersidir",
  "Dünya’nın eksen eğikliği yaklaşık 23,5 derecedir",
  "Mevsim çizelgesi tarım takvimini etkiler",
]
const dna = [
  "DNA, kalıtım bilgisini taşıyan moleküldür",
  "Gen, DNA üzerinde belirli bir bilgi parçasıdır",
  "Kromozom, DNA’nın paketlenmiş hâlidir",
  "İnsanda kromozomlar çiftler hâlinde bulunur",
  "Nükleotit, DNA’nın yapı birimidir",
  "Adenin timinle, guanin sitozinle eşleşir",
  "Üreme hücreleri kalıtımı yavruya taşır",
  "Çaprazlama, bezelye deneylerinde karakterin izlenmesidir",
  "Baskın karakter, çekinik karakterin yanında görünebilir",
  "Çekinik karakter iki kopya gelirse ortaya çıkabilir",
  "Mutasyon, DNA dizisindeki kalıcı değişimdir",
  "Modifikasyon, çevrenin geçici etkisidir ve genellikle kalıtılmaz",
  "Güneş yanığı bir modifikasyon örneği olabilir",
  "Orak hücre, bir gen değişiminin bedendeki sonucudur",
  "Adaptasyon, canlının yaşama şansını artıran kalıtsal özelliğidir",
  "Kutup ayısının kürkü bir adaptasyondur",
  "Varyasyon, tür içindeki kalıtsal farklılıktır",
  "Eşeyli üreme varyasyonu artırır",
  "Biyoteknoloji, canlıyı kullanarak ürün geliştirmeyi kapsar",
  "Aşı, bağışıklık sistemini hastalık etkenine hazırlar",
  "İnsülin, bakterilere gen aktarılarak üretilebilir",
  "Genetiği değiştirilmiş tohum tartışması fayda ve riski birlikte sorar",
  "Klonlama, genetik kopya üretme girişimidir",
  "DNA parmak izi kişiyi ayırt etmeye yardım eder",
  "Mutasyon her zaman zararlı olmak zorunda değildir",
  "Çevre, genin ortaya çıkışını etkileyebilir",
  "Sağlıklı yaşam, kalıtımı değiştirmez ama riski azaltabilir",
  "Bilimsel iddia, tek örnekle kanun olmaz",
  "Etik, bir uygulamanın yapılabilir olmasıyla doğru olmasını ayırır",
]
const basinc = [
  "Katıda basınç kuvvet bölü alandır",
  "Sivri topuk, geniş tabandan daha çok basınç yapar",
  "Kayak, alanı büyüterek karda batmayı azaltır",
  "Sıvı basıncı derinlikle artar",
  "Aynı derinlikte her yöne sıvı basıncı vardır",
  "Baraj duvarı altta daha kalındır",
  "Açık hava basıncı cıva sütununu yaklaşık 76 cm tutar",
  "Yükseğe çıkınca açık hava basıncı azalır",
  "Pipetle sıvı, ağız içindeki basınç düşünce yükselir",
  "Gaz basıncı, taneciklerin çarpmasıyla oluşur",
  "Kapalı kaptaki gaz ısınırsa basınç artabilir",
  "Lastik, sıcak havada daha şiş görünebilir",
  "Basınç birimi paskal olabilir",
  "Kuvvet aynı, alan küçülürse basınç artar",
  "Alan büyürse basınç azalır",
]
const endustri = [
  "Periyodik sistem elementleri artan atom numarasına göre dizer",
  "Aynı gruptaki elementler benzer kimyasal davranış gösterebilir",
  "Periyot, yatay sıradır",
  "Grup, düşey sütundur",
  "Metaller genelde ısı ve elektriği iletir",
  "Ametaller elektriği zayıf iletebilir",
  "Soy gazlar tepkimeye pek girmez",
  "Fiziksel değişimde madde aynı kalır, görünüş değişebilir",
  "Kâğıdı yırtmak fiziksel değişimdir",
  "Kimyasal değişimde yeni madde oluşur",
  "Demirin paslanması kimyasal değişimdir",
  "Mumun erimesi fiziksel, yanması kimyasaldır",
  "Yanma, maddenin oksijenle tepkimesidir",
  "Asitler turnusolü kırmızıya çevirebilir",
  "Bazlar turnusolü maviye çevirebilir",
  "Asit ve baz birleşince tuz ve su oluşabilir",
  "Mide asidi sindirime yardım eder, fazlası rahatsız eder",
  "Sabun bazik özellik taşıyabilir",
  "Limon suyu asidik bir karışımdır",
  "pH 7 nötre yakındır",
  "pH 7’den küçük asidik olabilir",
  "pH 7’den büyük bazik olabilir",
  "Asit metalle tepkimeye girip gaz çıkarabilir",
  "Endüstride sülfürik asit birçok ürünün girdisidir",
  "Gübre, bitkiye mineral sağlar ama fazlası suyu kirletir",
  "İlaç, dozunda yarar, fazlasında zehir olabilir",
  "Plastik, petrol ürünlerinden üretilebilir",
  "Geri dönüşüm endüstriyel ham maddeyi azaltabilir",
  "Kimyasal atık lavaboya dökülmez",
  "Etiket, asit mi baz mı olduğunu söyler",
  "Koruyucu gözlük asitle çalışmada şarttır",
  "Fiziksel ve kimyasal değişim aynı kapta art arda olabilir",
  "Element sembolü periyodik tablodan okunur",
  "Bileşik, elementlerin belirli oranda birleşmesidir",
]
const makine = [
  "Kaldıraç, destek noktasına göre kuvveti yola çevirir",
  "Makara, kuvvetin yönünü değiştirebilir",
  "Eğik düzlem, yükü daha uzun yolda daha küçük kuvvetle çıkarmaya yardım eder",
  "Vida, eğik düzlemin sarılmış hâlidir",
  "Çıkrık, kova çıkarmayı kolaylaştırır",
  "Basit makine işten kazanç sağlamaz, kuvvetten kazandırabilir",
  "Kuvvetten kazanç varsa yoldan kayıp vardır",
  "Makas bir kaldıraç örneğidir",
  "El arabası yükü kaldıraç gibi taşır",
  "Sürtünme, makinenin verimini düşürür",
]
const cevre8 = [
  "Fotosentez ışığı besine çevirir",
  "Solunum besindeki enerjiyi açığa çıkarır",
  "Besin zinciri üreticiden tüketiciye gider",
  "Enerji zincirde ısı olarak dağılır",
  "Madde döngüsü, elementin canlı ve cansız arasında dolaşmasıdır",
  "Karbon döngüsünde solunum karbondioksit verir",
  "Fotosentez karbondioksiti besine bağlar",
  "Azot, baklagillerin kökündeki bakterilerle toprağa bağlanabilir",
  "Su döngüsü buharlaşma ve yağışla sürer",
  "Fosil yakıt yakmak karbon döngüsüne hızlı karbondioksit ekler",
  "Sera etkisi doğal bir ısı tutmadır, fazlası ısınmayı artırır",
  "Orman kesmek hem yaşam alanını hem karbon tutmayı azaltır",
  "Geri dönüşüm maden ve enerji talebini düşürebilir",
  "Kompost, organik artığı toprağa döndürür",
  "LED aydınlatma aynı ışık için daha az enerji harcayabilir",
  "Yalıtım, kışın ısı kaybını azaltır",
  "Toplu taşıma kişi başı yakıtı düşürebilir",
  "Gıda israfı su ve tarla israfıdır",
  "Yenilenebilir enerji yakıt stokunu zorlamaz",
  "Baraj, enerji üretirken vadideki yaşamı da değiştirir",
  "Rüzgâr türbini kuş rotasına dikkat edilerek kurulmalıdır",
  "Güneş paneli çatıda yakıt yakmadan çalışır",
  "Asit yağmuru bacadaki gazların suyla birleşmesinden gelebilir",
  "Ozon tabakası morötesi ışığı süzer",
  "Tek kullanımlık plastik deniz canlısına dolanabilir",
  "Atık pil toprağa ağır metal bırakabilir",
  "Su tasarrufu, barajdaki suyu da korur",
  "Sürdürülebilir şehir, yürünebilir mesafe tasarlar",
  "Bilimsel çevre kararı, ölçüme dayanır",
  "Bireysel tercih ile kamu kuralı birlikte işe yarar",
]
const elektrik8 = [
  "Aynı cins yükler iter, zıt yükler çeker",
  "Yük, yeni yaratılmaz, ayrılır veya aktarılır",
  "İletken, yükün hareketine izin verir",
  "Yalıtkan, yükü yerinde tutar",
  "Topraklama fazla yükü uzaklaştırır",
  "Elektrik akımı, yüklerin bir yöndeki hareketidir",
  "Gerilim, yükleri harekete zorlayan etkidir",
  "Direnç akımı zorlar",
  "Ohm yasası gerilim, akım ve direnci ilişkilendirir",
  "Seri devrede akım tek yoldan gider",
  "Paralel devrede kollar ayrı yol bulur",
  "Sigorta aşırı akımda yolu keser",
  "Kısa devre direnci düşürüp ısıyı tehlikeli artırır",
  "Elektrik enerjisi güç çarpı zamanla ilişkilidir",
  "Kilowatt saat, evdeki enerji birimidir",
  "Boşta yanan lamba enerjiyi ısı ve ışığa harcar",
  "Verimli araç aynı iş için daha az enerji ister",
  "Islak elle prize dokunulmaz",
  "Yıldırımsavar yükü toprağa iletir",
  "Pil kimyasal enerjiyi elektrik enerjisine çevirir",
  "Akü tekrar doldurulabilir",
  "Manyetik etki, akım geçen telin çevresinde oluşabilir",
  "Elektrik motoru elektrik enerjisini harekete çevirir",
  "Jeneratör hareketi elektrik enerjisine çevirebilir",
  "Ev tesisatı paralel kurulur, bir lamba sönünce öteki yanabilir",
  "Kaçak akım rolesi çarpılma riskinde yolu keser",
]
const senlik = [
  "Proje sorusu ölçülebilir olmalıdır",
  "Varsayım, denenecek bir tahmindir",
  "Kontrollü deneyde bir değişken değiştirilir",
  "Bağımlı değişken sonuçta ölçülür",
  "Bağımsız değişken araştırmacının değiştirdiğidir",
  "Kontrol grubu, karşılaştırmanın dayanağıdır",
  "Tek deneme sonuç için yetersiz kalabilir",
  "Tablo, ölçümleri sıralı gösterir",
  "Grafik, eğilimi cümleden hızlı gösterir",
  "Birim yazılmazsa sayı anlamsız kalır",
  "Hata payı, ölçümün kesinliğini söyler",
  "Kaynak, iddianın dayanağını gösterir",
  "Poster, sonucu abartmadan anlatır",
  "Etik, canlıya ve veriye zarar vermemeyi sorar",
  "Sınırını söylemek, projenin gücünü azaltmaz",
]
const yil8 = [
  "Mevsimi Güneş’e uzaklık sanmak",
  "Mutasyon ile modifikasyonu bir tutmak",
  "Basıncı yalnız kuvvet sanmak",
  "Fiziksel değişimi kimyasal sanmak",
  "Basit makinenin iş ürettiğini sanmak",
]

export const fen78 = {
  "7|Uzay çağı": daily("Uzay", "Uzay araştırması teleskop, uydu ve araçlarla veri toplar. Işık yılı bir zaman aralığı değil, ışığın bir yılda aldığı uzaklıktır. Türkiye’nin uyduları iletişim ve yer gözlemi için kullanılır.", "Işık yılını saat gibi bir süre sanmak uzaklığı zaman yapar.", ["Işık yılı bir uzaklıktır", "Uydu Dünya çevresinde veri gönderir", "Uzayda ses iletilmez"], ["Teleskop sesi büyütür", "Roket oksijensiz de insanı korur", "Göktaşı bir yıldızdır"], uzay),
  "7|Kuvvet, iş ve enerji": daily("İş ve enerji", "İş, kuvvetin yol boyunca etkimesidir. Yol yoksa veya yol kuvvete dikse o kuvvet iş yapmaz. Enerji iş yapabilme yeteneğidir ve biçim değiştirerek aktarılır, yok olmaz.", "Her kuvveti iş saymak, dik kuvveti de işe yazar.", ["İş kuvvet çarpı yoldur", "Enerji biçim değiştirir", "Sürtünme bir kısmı ısıya çevirir"], ["Yol olmadan da iş vardır", "Enerji işlem sonunda yok olur", "Potansiyel yalnız hareket demektir"], isEnerji),
  "7|Enerji dönüşümleri": daily("Dönüşüm", "Enerji bir biçimden ötekine geçer. Dönüşümde bir kısım enerji ısı olarak dağılabilir. Dağılan enerji yok olmamıştır, işe çevrilmesi zorlaşmıştır.", "Dönüşümü kayıpsız sanmak verimi yüzde yüz sayar.", ["Elektrik ısıya dönebilir", "Hareket elektriğe dönebilir", "Isıya dağılan enerji de enerjidir"], ["Enerji dönüşünce yok olur", "Besin doğrudan elektriktir", "Her araç yüzde yüz verimlidir"], donusum),
  "7|Sindirim sistemi": daily("Sindirim", "Sindirim, besini kana geçebilecek küçüklüğe ayırmaktır. Ağızda başlar, midede sürer, ince bağırsakta emilir. Karaciğer ve pankreas bu yola salgı verir.", "Sindirimi yalnız midede bitmiş sanmak bağırsaktaki emilimi atlar.", ["Emilim ince bağırsaktadır", "Diş mekanik sindirime yardım eder", "Lif bağırsak hareketini destekler"], ["Yemek borusu besini sindirir", "Karaciğer doğrudan çiğner", "Kalın bağırsak esas emilim yeridir"], sindirim),
  "7|Dolaşım sistemi": daily("Dolaşım", "Kalp kanı pompalar. Atardamar kalpten uzaklaşır, toplardamar kalbe döner, kılcal damar hücreyle alışveriş yapar. Kan hücreleri oksijen, savunma ve pıhtılaşma görevleri taşır.", "Bütün damarları aynı yöne sanmak atar ile topları karıştırır.", ["Kalp kanı pompalar", "Alyuvar oksijen taşır", "Kılcal damar alışveriş yeridir"], ["Toplardamar kalpten uzaklaşır", "Nabız bir sıcaklık birimidir", "Kan yalnız su taşır"], dolasim),
  "7|Solunum sistemi": daily("Solunum", "Soluk alma havayı akciğere getirir. Alveollerde oksijen kana geçer, karbondioksit dışarı verilir. Hücre solunumu ise besinden enerji çıkarmaktır; ikisi aynı adım değildir.", "Solunum ile fotosentezi ters işlem diye aynı organda sanmak yanlıştır.", ["Oksijen kana akciğerde geçer", "Diyafram nefesi yönetir", "Hücre solunumu enerji üretir"], ["Burun oksijen üretir", "Sigara alveolü güçlendirir", "Solunum fotosentezin aynısıdır"], solunum),
  "7|Boşaltım sistemi": daily("Boşaltım", "Böbrek kanı süzerek idrar oluşturur. Deri ter, akciğer karbondioksit atarak boşaltıma katılır. Boşaltım, sindirilmeyen katı artık değildir.", "İdrar ile dışkıyı aynı sistem sanmak iki yolu karıştırır.", ["Böbrek kanı süzer", "Ter, su ve tuz atabilir", "Su içmek süzmeye yardım eder"], ["Akciğer idrar üretir", "Boşaltım sindirim artığıdır", "Tuz böbreği dinlendirir"], bosaltim),
  "7|Işığın kırılması": daily("Kırılma", "Işık bir ortamdan başka bir ortama geçerken hızı değişirse yönü de değişebilir. Buna kırılma denir. Tam yansıma, ışığın sınır açısından sonra öteki ortama geçemeyip döndüğü durumdur.", "Kırılan kaşığı gerçekten kırık sanmak görüntüyü madde sanmaktır.", ["Kırılma yön değişimidir", "Kaşık kırık görünür ama bütün kalır", "Tam yansıma bir sınır olayıdır"], ["Kırılma yansımadır", "Işık her ortamda aynı hızdadır", "Havuz dibi olduğundan uzaktır"], kirilma),
  "7|Mercekler": daily("Mercek", "İnce kenarlı mercek ışığı toplayabilir, kalın kenarlı mercek dağıtabilir. Göz kusurunda mercek, görüntüyü ağa düşürecek biçimde seçilir.", "İki merceği aynı sanmak büyüteç ile dağılmayı karıştırır.", ["İnce kenarlı mercek toplar", "Kalın kenarlı mercek dağıtabilir", "Mercek ışığı geçirerek kırar"], ["Büyüteç kalın kenarlıdır", "Mercek ışık üretmez diye kırmaz", "Yanlış mercek göze zarar vermez"], mercek),
  "7|Maddenin tanecikli yapısı": daily("Atom", "Atom, elementin kimyasal özelliğini taşıyan küçük birimidir. Molekül, atomların belirli biçimde bağlanmasıyla oluşur. Model, görünmeyeni anlatmak içindir.", "Atomu gözle görülen bir toz sanmak modeli yanlış ölçekler.", ["Element tek cins atomdur", "Molekül atomların bağlanmasıdır", "Atom modelle anlatılır"], ["Su bir elementtir", "Atom çıplak gözle seçilir", "Molekül katı olamaz"], atom),
  "7|Saf maddeler": daily("Saf madde", "Element tek cins atomdan, bileşik belirli oranda birleşmiş elementlerden oluşur. Erime noktası, kaynama noktası ve yoğunluk saf madde için ayırt edici olabilir. Kütle ve hacim miktara bağlıdır, ayırt edici değildir.", "Tuzlu suyu bileşik sanmak karışımı saf maddeye katar.", ["Su bir bileşiktir", "Erime noktası ayırt edici olabilir", "Kütle ayırt edici değildir"], ["Altın bir karışımdır", "Hacim maddeyi tanıtır", "Bileşik fiziksel yolla elementine ayrılır"], saf),
  "7|Karışımlar": daily("Karışım", "Homojen karışımda her yer aynı görünür, heterojende parçalar seçilir. Derişim, çözeltideki çözünen oranıdır. Çözelti bir karışımdır, yeni bir bileşik değildir.", "Koyu rengi her zaman saf madde sanmak derişimi atlar.", ["Şekerli su homojendir", "Derişim çözünen oranıdır", "Su eklemek seyreltir"], ["Kum-su homojendir", "Derişik, çözücüsü çok olandır", "Çözelti elementtir"], karisim),
  "7|Karışımları ayırma": daily("Ayırma", "Ayırma yöntemi, bileşenlerin mıknatıs, çözünürlük, kaynama veya tane boyu gibi farkına göre seçilir. Yanlış yöntem karışımı ayırmaz, yeni bir karışım yapabilir.", "Her karışımı süzmek, çözünmüş tuzu kâğıdın üstünde bırakmaz.", ["Mıknatıs demiri ayırır", "Buharlaştırma tuzu bırakır", "Yöntem özelliğe göre seçilir"], ["Süzgeç tuzu tutar", "Her karışım mıknatısla ayrılır", "Yöntem fark etmez"], ayirma),
  "7|Elektriklenme": daily("Yük", "Sürtünme, dokunma ve etki ile yükler ayrılabilir. Aynı cins yükler iter, zıt yükler çeker. Elektriklenme yeni yük yaratmak değil, var olan yükü ayırmak veya aktarmaktır.", "Çekilen her cismi zıt yüklü sanmak, nötr cismin de çekilebileceğini unutur.", ["Aynı yükler iter", "Zıt yükler çeker", "Topraklama yükü uzaklaştırır"], ["Sürtünme yükü yok eder", "Plastik her zaman iletkendir", "Yıldırım yüksüz bir ışıktır"], yukle),
  "7|Sürdürülebilir yaşam ve enerji": daily("Sürdürülebilirlik", "Yenilenebilir kaynaklar Güneş, rüzgâr ve akan su gibi yeniden gelen akımlardır. Fosil yakıt stokları tükenir. Besin zincirinde enerji bir halkadan ötekine ısı olarak dağılır.", "Yenilenebilir kaynağı zararsız diye sınırsız kurmak, kurulumun doğaya etkisini siler.", ["Güneş yenilenebilir kaynaktır", "Ayrıştırıcı maddeyi döndürür", "Tasarruf kaynak ömrünü uzatır"], ["Kömür kısa sürede yenilenir", "Zincirde enerji artar", "İsraf yalnız parayı ilgilendirir"], surdur),
  "7|Yıl sonu tekrarı": daily("Yedinci sınıf fen", "Yıl sonunda iş, mercek, saf madde ve kırılma ayrı ayrı hatırlanır. Bir örneğin hangi kavrama ait olduğu, sayıyı yazmadan önce sorulur.", "Benzeyen sözcükleri aynı olaya bağlamak kavramı kaydırır.", ["İş yol ister", "İnce kenarlı mercek toplar", "Tuzlu su karışımdır"], ["Kırılma yansımadır", "Element karışımdır", "Enerji dönüşünce yok olur"], yil7),
  "8|Mevsimler ve iklim": daily("Mevsim", "Mevsimler, Dünya’nın eksen eğikliği ve Güneş çevresindeki dolanımıyla oluşur. Güneş’e uzaklığın azalıp artması asıl neden değildir. Hava kısa sürenin durumu, iklim uzun yılların ortalamasıdır.", "Bir yağmurlu günü iklim saymak, ortalamayı tek güne bağlar.", ["Eksen eğikliği mevsimi doğurur", "Hava ile iklim ayrıdır", "Güney yarım kürede mevsim terstir"], ["Yaz, Güneş’e en yakın olunan gündür", "Ekinoksta gece hiç olmaz", "İklim bir günün hava raporudur"], mevsim),
  "8|DNA ve genetik kod": daily("DNA", "DNA kalıtım bilgisini taşır. Gen bu bilginin bir parçası, kromozom ise DNA’nın paketli hâlidir. Mutasyon dizideki kalıcı değişim, modifikasyon çevrenin genellikle kalıtılmayan etkisidir. Adaptasyon yaşama şansını artıran kalıtsal özelliktir.", "Güneş yanığını mutasyon sanmak, geçici etkiyi kalıta yazar.", ["DNA kalıtım taşır", "Mutasyon diziyi değiştirir", "Modifikasyon genellikle kalıtılmaz"], ["Adaptasyon bir günde bronzlaşmaktır", "Gen ile kromozom aynı uzunluktadır", "Çekinik karakter hiç ortaya çıkmaz"], dna),
  "8|Basınç": daily("Basınç", "Katıda basınç, kuvvetin alana bölümüdür. Alan küçülürse basınç artar. Sıvı basıncı derinlikle artar. Gaz basıncı taneciklerin çarpmasından doğar ve sıcaklıkla artabilir.", "Basıncı yalnız kuvvet sanmak, kayakta batmamanın nedenini gizler.", ["Basınç kuvvet bölü alandır", "Sıvı basıncı derinlikle artar", "Alan büyüyünce basınç azalır"], ["Sivri topuk basıncı azaltır", "Yüksekte hava basıncı artar", "Gazın basıncı yoktur"], basinc),
  "8|Madde ve endüstri": daily("Madde ve endüstri", "Periyodik sistem elementleri atom numarasına göre dizer. Fiziksel değişimde madde aynı kalır, kimyasal değişimde yeni madde oluşur. Asit ve baz turnusol ve pH ile ayırt edilebilir. Endüstride kullanılan maddenin dozu ve atığı güvenlik işidir.", "Mumun erimesini yanmayla bir tutmak iki değişimi karıştırır.", ["Paslanma kimyasaldır", "Kâğıt yırtmak fizikseldir", "Asit ile baz tuz ve su verebilir"], ["Her element metaldir", "pH 7 kuvvetli asittir", "Asit lavaboya dökülür"], endustri),
  "8|Basit makineler": daily("Basit makine", "Basit makineler kuvvetin büyüklüğünü veya yönünü değiştirir. Kuvvetten kazanç varsa yoldan kayıp vardır. Toplam iş, sürtünme yok sayılırsa korunur; makine enerji üretmez.", "Makinenin işten kazanç sağladığını sanmak enerjiyi yoktan var eder.", ["Kuvvet kazancı yol kaybı getirir", "Eğik düzlem kuvveti küçültebilir", "Makine enerji üretmez"], ["Makara iş üretir", "Vida bir kaldıraç değildir", "Sürtünme verimi artırır"], makine),
  "8|Enerji dönüşümleri ve çevre": daily("Çevre ve enerji", "Fotosentez ışığı besine, solunum besini enerjiye çevirir. Madde döngülerle dolaşır, enerji ise zincirde ısı olarak dağılır. Fosil yakıtın hızlı yanması karbon döngüsüne ek yük bindirir.", "Enerjinin de madde gibi hiç dağılmadan döndüğünü sanmak besin piramidini düzleştirir.", ["Fotosentez karbondioksit bağlar", "Enerji zincirde ısıya dağılır", "Geri dönüşüm talebi azaltabilir"], ["Solunum oksijen üretir", "Sera etkisi her zaman zararsızdır", "İsraf yalnız mutfağı ilgilendirir"], cevre8),
  "8|Elektrik yükleri ve elektrik enerjisi": daily("Elektrik", "Aynı yükler iter, zıt yükler çeker. Akım yüklerin yönlü hareketi, direnç bu hareketi zorlayan özelliktir. Ev tesisatı paraleldir. Sigorta ve kaçak akım rolesi aşırı akımda yolu keser.", "Seri ile paraleli karıştırmak, bir lambanın sönünce evi karartacağını sanır.", ["Zıt yükler çeker", "Ev tesisatı paraleldir", "Sigorta aşırı akımda keser"], ["Aynı yükler çeker", "Kısa devre güvenlidir", "Kilowatt saat bir kuvvettir"], elektrik8),
  "8|Bilim şenliği": daily("Bilim şenliği", "Bir proje, ölçülebilir soru, kontrollü değişken ve tekrarlanan ölçüm ister. Sonuç, birimin ve sınırın yazıldığı cümleyle anlatılır. Tek deneme kanun değildir.", "Kontrolsüz denemeyi kanıt sanmak değişkeni gizler.", ["Bir değişken değiştirilir", "Birim yazılmazsa sayı eksiktir", "Sınırını söylemek dürüstlüktür"], ["Varsayım sonuçtur", "Tek ölçüm yeter", "Kaynak süs içindir"], senlik),
  "8|Yıl sonu tekrarı": daily("Sekizinci sınıf fen", "Yıl sonunda mevsim, mutasyon, basınç ve değişim türü ayrı sorulur. Her kavram kendi örneğine bağlanır.", "Tek güne bakıp iklim, tek yanığa bakıp mutasyon demek kavramı kaydırır.", ["Mevsim eksen eğikliğindendir", "Modifikasyon genellikle kalıtılmaz", "Basınç alanla değişir"], ["Basit makine iş üretir", "Paslanma fizikseldir", "Hava ile iklim aynıdır"], yil8),
}
