import { daily } from "./fen-auto.js"

const g6sun = [
  "Merkür Güneş’e en yakın gezegendir",
  "Venüs’ün yüzeyi çok sıcaktır",
  "Dünya’nın uydusu Ay’dır",
  "Mars’a kızıl gezegen denir",
  "Jüpiter Güneş sisteminin en büyük gezegenidir",
  "Satürn’ün belirgin halkaları vardır",
  "Uranüs ve Neptün gaz ve buz devleridir",
  "Güneş tutulmasında Ay, Güneş ile Dünya arasına girer",
  "Ay tutulmasında Dünya’nın gölgesi Ay’a düşer",
  "Tutulma her yeni Ay’da olmaz, yörünge düzlemi şarttır",
  "Güneş tutulmasına çıplak gözle bakılmaz",
  "Asteroit kuşağı Mars ile Jüpiter arasındadır",
  "Kuyruklu yıldızın kuyruğu Güneş’e yaklaşınca belirginleşir",
  "Gezegenler kendi ışığını üretmez",
  "Güneş sisteminin merkezi Güneş’tir",
]
const bileske = [
  "Aynı yöne 4 N ve 6 N kuvvet uygulanır",
  "Zıt yöne 9 N ve 4 N kuvvet uygulanır",
  "Eşit büyüklükte zıt iki kuvvet duran cismi yerinde bırakabilir",
  "İp çekme yarışında 30 N ve 22 N vardır",
  "Sürtünme, net kuvveti küçültebilir",
  "Aynı yönlü kuvvetler toplanır",
  "Zıt kuvvetlerde büyük olandan küçük olan çıkarılır",
  "Net kuvvet sıfırsa hız değişmeyebilir",
  "Net kuvvet varsa cisim hızlanır, yavaşlar veya yön değiştirir",
  "Dinamometrede okunan değer kuvvetin büyüklüğüdür",
]
const surat = [
  "10 saniyede 50 metre giden bisiklet",
  "Hızın yönü sağa, sürat ise yalnız büyüklüktür",
  "Aynı süratte dönen bir virajda hızın yönü değişir",
  "Duran cismin sürati sıfırdır",
  "Yol bölü zaman sürati verir",
]
const ureme = [
  "Çiçekli bitkide tozlaşma polenlerin taşınmasıdır",
  "Döllenme, sperm ile yumurtanın birleşmesidir",
  "Tohum, yeni bitkinin taslağını taşır",
  "Çimlenme için su, uygun sıcaklık ve oksijen gerekir",
  "Fasulye tohumu çimlenirken önce kök çıkar",
  "Eşeysiz üremede yavru tek ataya benzer",
  "Patatesin yumrusundan yeni bitki çıkabilir",
  "Hayvanlarda iç döllenme vücut içinde olur",
  "Dış döllenmede yumurta ve sperm suda buluşabilir",
  "Başkalaşımda iribaş kurbağaya dönüşür",
  "Kelebek yumurta, tırtıl, pupa ve ergin evresi geçirir",
  "İnsan yavrusu anne vücudunda gelişir",
  "Ergenlikte vücut hızlı değişir",
  "Büyüme, kütlenin ve boyun artmasıdır",
  "Gelişme, yapının olgunlaşmasıdır",
  "İkizlerden bazıları döllenmiş tek yumurtanın bölünmesidir",
  "Arı kolonisinde görevler üreme ile ilişkilidir",
  "Tohum dağılmazsa yeni bitki ana bitkinin dibinde kalır",
  "Yavru bakımı, doğumdan sonra yaşam şansını artırır",
]
const denet = [
  "Beyin, istemli hareketi yönetir",
  "Omurilik bazı reflekslerin merkezidir",
  "Göz, ışığı sinir iletisine çevirir",
  "Kulak, sesi dengede de rol alır",
  "Hormonlar kanla taşınır",
  "İnsülin kan şekerinin düzenine katılır",
  "Adrenalin heyecan anında salgılanır",
  "Sinir sistemi hızlı, hormon sistemi daha uzun süreli etki eder",
  "Refleks, tehlikede düşünmeden korur",
  "Duyu organı bozulursa beyne giden bilgi eksilir",
]
const yansima = [
  "Düz aynada gelen açı yansıyan açıya eşittir",
  "Düz ayna görüntüyü aynı boyda gösterir",
  "Aynadaki görüntü sağ ile solu yer değiştirmiş gibi durur",
  "Işık aynaya çarpınca yön değiştirir",
  "Pürüzlü yüzey dağınık yansıma yapar",
  "Periskopta düz aynalar ışığı döndürür",
  "Gelen ışın, normal ve yansıyan ışın aynı düzlemdedir",
  "Ayna kirlenirse görüntü zayıflar",
  "Düzlem aynada görüntü sanaldır, perdenin üstüne düşmez",
  "Fener ışığı aynadan eşit açıyla döner",
  "Su yüzeyi sakinse ayna gibi yansıtır",
  "Çoklu ayna görüntüyü çoğaltabilir",
  "Yansıma, ışığın soğurulması değildir",
  "Karanlık odada ayna kendi ışığını üretmez",
]
const ayna = [
  "Çukur ayna ışığı bir bölgede toplayabilir",
  "Tümsek ayna geniş alan gösterir, görüntüyü küçültür",
  "Araçların yan aynası tümsektir",
  "Makasın sapına Güneş’i odaklamak yangın çıkarabilir",
  "Ayna türü, güvenlik için amaca göre seçilir",
]
const sogur = [
  "Siyah kumaş Güneş’te daha çok ısınır",
  "Beyaz kumaş ışığın çoğunu yansıtır",
  "Koyu renk kışın ısıyı daha çok tutabilir",
  "Güneş paneli ışığı soğurup enerjiye çevirir",
  "Ayna soğurmak için değil yansıtmak için seçilir",
  "Mat yüzey parlak yüzeye göre daha çok soğurabilir",
  "Soğurulan ışık maddenin ısısını artırabilir",
  "Renk, yansıyan ışığın türüyle ilişkilidir",
  "Koyu araba yazın daha çabuk ısınır",
  "Beyaz badana evin dışını serin tutmaya yardım eder",
  "Işık yoksa soğurma da olmaz",
  "Saydam cam ışığın çoğunu geçirir, azını soğurur",
  "Enerji dönüşümünde ışık ısıya dönebilir",
  "Fotosentez, soğurulan ışığı besine çevirir",
  "Gölgede kalan koyu taş, güneştekine göre daha az ısınır",
]
const genles = [
  "Yazın raylar genleşmesin diye aralıklı döşenir",
  "Sıcak su metal kapağı gevşetebilir",
  "Soğukta hava balonu büzülür",
  "Termometrede sıvı ısınınca yükselir",
  "Köprü boşlukları genleşme payıdır",
  "Cam kavanoz ani sıcak-soğuk farkında çatlayabilir",
  "Elektrik telleri yazın sarkar",
  "Büzülen metal kapak kışın sıkışabilir",
  "Genleşme hâl değişimi değildir",
  "Farklı metaller aynı ısıda farklı genleşebilir",
]
const kaynama = [
  "Saf su 1 atmosferde 100°C’de kaynar",
  "Kaynama süresince sıcaklık sabit kalabilir",
  "Erime süresince buz-su karışımının sıcaklığı sabittir",
  "Tuzlu suyun kaynama noktası saf sudan farklıdır",
  "Hâl değişim noktasında verilen ısı sıcaklığı yükseltmeyebilir",
  "Donma, erimenin tersi yöndedir",
  "Basınç değişirse kaynama noktası değişebilir",
  "Karışımın erime noktası saf maddeninkinden ayrılabilir",
  "Termometre kaynarken bir süre aynı dereceyi gösterebilir",
  "Hâl değişim ısısı sıcaklık artışı değildir",
]
const yogun = [
  "Kütlesi 20 g, hacmi 10 cm³ olan tahta",
  "Kütlesi 40 g, hacmi 10 cm³ olan taş",
  "Su üstünde kalan tahta sudan küçük yoğunluktadır",
  "Batan taş sudan büyük yoğunluktadır",
  "Yoğunluk kütle bölü hacimdir",
  "Aynı hacimde kütlesi büyük olan daha yoğundur",
  "Geminin çelik olmasına rağmen yüzmesi biçim ve ortalama yoğunlukla ilgilidir",
  "Yumurta tuzlu suda daha kolay yüzer",
  "Sıcak hava balonu, ısınan havanın yoğunluğu azalınca yükselir",
  "1 g/cm³ yoğunluk suya yakındır",
  "Hacim artıp kütle aynı kalırsa yoğunluk azalır",
  "Kütle artıp hacim aynı kalırsa yoğunluk artar",
  "Zeytinyağı sudan küçük yoğunlukta olduğu için üstte durur",
  "Demir para batar, çünkü yoğunluğu sudan büyüktür",
  "Buz, sıvı sudan küçük yoğunlukta olduğu için yüzer",
  "Yoğunluk birimi g/cm³ olabilir",
  "Aynı madde için yoğunluk ayırt edici olabilir",
  "İçi boş topun ortalama yoğunluğu düşer",
  "Batma-yüzme yalnız ağırlığa bakılarak kararlaştırılmaz",
  "Terazi kütleyi, dereceli silindir hacmi buldurur",
]
const ilet = [
  "Bakır tel ampulü yakar",
  "Plastik çubuk devreyi tamamlamaz",
  "Islak el prize yaklaştırılmaz",
  "İletken ile yalıtkan güvenlik için ayırt edilir",
]
const direnc = [
  "Uzun telin direnci kısa telden büyük olabilir",
  "İnce tel kalın tele göre daha çok direnç gösterebilir",
  "Ampulün parlaklığı direnç düşünce artabilir",
  "Direnç, akımı zorlayan özelliktir",
  "Aynı pilde küçük dirençli yol daha parlak ampul verebilir",
  "Telin cinsi direnci değiştirir",
  "Kısa devre direnci tehlikeli biçimde düşürür",
  "Reosta direnci ayarlamaya yarar",
  "Isınan telin direnci değişebilir",
  "Seri bağlanan iki ampul daha sönük yanabilir",
  "Paralel bağlamada her ampul kendi yolunu bulur",
  "Direnç ohm ile anlatılır",
  "Pil gerilimi artarsa aynı dirençte akım artabilir",
  "Güvenlik sigortası aşırı akımda yolu keser",
  "İnce ve uzun nikrom tel daha çok ısınabilir",
]
const biyo = [
  "Bir ormanda çok sayıda tür yaşaması çeşitliliktir",
  "Arı, çiçeklerin tozlaşmasına yardım eder",
  "Kurbağa hem böcek yer hem yılana yem olur",
  "Sulak alan kurutulursa türler yerinden olur",
  "Aşırı avlanma balık soyunu azaltır",
  "Yabancı tür, yerli türün besinini tüketebilir",
  "Millî park canlıları korumak için sınırlanır",
  "Yangın hem bitkiyi hem yuvayı yok eder",
  "Çeşitlilik azalınca besin ağı zayıflar",
  "Tohum bankası türü geleceğe saklar",
  "Kirli akarsu balığın üremesini bozar",
  "Her türün ekosistemde bir görevi vardır",
]
const cevre = [
  "Gereksiz ışığı kapatmak enerji tasarrufudur",
  "Tek kullanımlık poşet yerine bez torba",
  "Atık yağı lavaboya dökmek suyu kirletir",
  "Toplu taşıma, kişi başı yakıtı azaltabilir",
  "Ağaç dikmek hem gölge hem yaşam alanı verir",
  "Gıda israfı, boşa harcanan su ve tarla demektir",
  "Geri dönüşüm ham madde çıkarmayı azaltır",
  "Fabrika filtresi havaya karışan isi keser",
  "Bireysel tercih, tüketim zincirini etkiler",
  "Sürdürülebilirlik, gelecek kuşağın hakkını da gözetir",
]
const yil6 = [
  "Güneş tutulmasında sıraya Ay’ı yanlış koymak",
  "Sürat ile hızın yönünü karıştırmak",
  "Yoğunluğu kütle sanmak",
  "Çukur aynayla Güneş’i yakmak",
  "Plastiği iletken diye denemek",
]

export const upperFen = {
  "6|Güneş sistemi ve tutulmalar": daily("Güneş sistemi", "Güneş sistemi, merkezdeki Güneş ile onun çevresinde dolanan gezegenler, uydular ve küçük gökcisimlerinden oluşur. Tutulma, ışık kaynağı, engel ve gölgenin aynı doğrultuya gelmesidir.", "Her yeni Ay’ı Güneş tutulması sanmak, yörünge eğimini unutmaktır.", ["Gezegen ışığı yansıtır", "Güneş tutulmasında Ay aradadır", "Ay tutulmasında Dünya’nın gölgesi Ay’a düşer"], ["Ay bir gezegendir", "Tutulmaya çıplak bakılır", "Güneş Dünya’nın uydusudur"], g6sun),
  "6|Bileşke kuvvet": daily("Bileşke", "Aynı yönlü kuvvetler toplanır, zıt yönlü kuvvetlerde büyükten küçük çıkarılır. Net kuvvet sıfırsa cismin hızı değişmeyebilir.", "Zıt kuvvetleri de toplamak net kuvveti şişirir.", ["Aynı yönlü kuvvetler toplanır", "Zıt kuvvetlerde fark alınır", "Net kuvvet ivmeyi belirler"], ["Kuvvetler her zaman toplanır", "Net kuvvet kilogramdır", "Zıt kuvvetler birbirini büyütür"], bileske),
  "6|Sabit sürat ve hız": daily("Sürat", "Sürat, alınan yolun zamana bölümüdür ve yalnız büyüklük taşır. Hızın ise yönü de vardır. Virajda sürat sabit kalırken hız değişebilir.", "Hız ile sürati aynı ok sanmak yönü siler.", ["Sürat yol bölü zamandır", "Hızın yönü vardır", "Duran cismin sürati sıfırdır"], ["Sürat bir kuvvettir", "Virajda hız hiç değişmez", "Zaman yol ile çarpılır"], surat),
  "6|Üreme, büyüme ve gelişme": daily("Üreme", "Üreme, canlının soyunu sürdürmesidir. Eşeyli üremede döllenme vardır. Büyüme kütle ve boy artışı, gelişme ise yapının olgunlaşmasıdır.", "Büyüme ile gelişmeyi aynı saymak, başkalaşımı boy uzaması sanmaktır.", ["Döllenme iki hücrenin birleşmesidir", "Çimlenme su ve sıcaklık ister", "Başkalaşım evre değiştirir"], ["Tohum cansız bir taştır", "Eşeysiz üremede iki ata şarttır", "İribaş doğrudan ergindir"], ureme),
  "6|Denetleyici ve düzenleyici sistem": daily("Denetim", "Sinir sistemi uyarıyı hızla iletir. İç salgı bezleri hormon üretir ve kan yoluyla daha uzun süreli etki eder. Refleks, tehlikede vücudu korur.", "Her tepkiyi bilinçli karar sanmak refleksi açıklayamaz.", ["Beyin istemli hareketi yönetir", "Hormon kanla taşınır", "Refleks hızlı korur"], ["Hormon kemik içinden yürür", "Omurilik görmezden gelinir", "Göz ışığı kendisi üretir"], denet),
  "6|Işığın yansıması": daily("Yansıma", "Düz aynada gelme açısı yansıma açısına eşittir. Ayna ışık üretmez, gelen ışığı döndürür. Pürüzlü yüzey ışığı dağınık yansıtır.", "Aynanın karanlıkta kendi kendine parladığını sanmak kaynağı karıştırır.", ["Gelme açısı yansıma açısına eşittir", "Ayna ışık üretmez", "Pürüz dağınık yansıma yapar"], ["Ayna bir ışık kaynağıdır", "Açıların eşit olması gerekmez", "Karanlıkta ayna ışık saçar"], yansima),
  "6|Aynalar": daily("Ayna türü", "Çukur ayna ışığı toplayabilir, tümsek ayna görüş alanını genişletip görüntüyü küçültür. Tür, işe göre seçilir. Güneş’i çukur aynayla odaklamak yangın riskidir.", "Her aynayı düz ayna sanmak araç aynasının görevini bozar.", ["Tümsek ayna alanı genişletir", "Çukur ayna toplayabilir", "Güneş çukur aynaya tutulmaz"], ["Yan ayna görüntüyü büyütmek için düzdür", "Çukur ayna her zaman küçültür", "Ayna türü güvenliği ilgilendirmez"], ayna),
  "6|Işığın soğurulması": daily("Soğurma", "Koyu ve mat yüzeyler ışığın daha çoğunu soğurup ısınabilir. Açık ve parlak yüzeyler daha çok yansıtır. Soğurulan ışık ısıya dönüşebilir.", "Siyahın ışık ürettiğini sanmak soğurmayı kaynak yapar.", ["Siyah yüzey daha çok soğurur", "Beyaz yüzey daha çok yansıtır", "Soğuran madde ısınabilir"], ["Beyaz her zaman daha çok ısınır", "Ayna ışığı soğurmak için konur", "Renk ısıyı etkilemez"], sogur),
  "6|Genleşme ve büzülme": daily("Genleşme", "Maddeler ısınınca genleşir, soğuyunca büzülür. Ray aralığı ve köprü payı bu yüzden bırakılır. Genleşme, erime demek değildir.", "Isınan her maddeyi erimiş sanmak hâl değişimini genleşmeyle karıştırır.", ["Isınınca genleşme olur", "Soğuyunca büzülme olur", "Genleşme erime değildir"], ["Soğukta raylar uzar", "Kapak ısıtılınca sıkışır", "Balon soğukta şişer"], genles),
  "6|Hâl değişim noktaları": daily("Kaynama", "Saf bir madde sabit basınçta belirli sıcaklıkta erir ve kaynar. Bu sırada verilen ısı sıcaklığı yükseltmeyebilir, hâl değişimine harcanır.", "Kaynarken sıcaklığın sürekli artacağını sanmak termometreyi yanlış okutur.", ["Kaynama noktası ayırt edici olabilir", "Hâl değişirken sıcaklık sabit kalabilir", "Karışımın noktası saftan ayrılabilir"], ["Her sıvı 100 derecede kaynar", "Erirken sıcaklık hızla artar", "Tuz kaynama noktasını değiştirmez"], kaynama),
  "6|Yoğunluk": (n) => daily("Yoğunluk", "Yoğunluk, birim hacimdeki kütledir ve kütle bölü hacim diye bulunur. Sıvıdan büyük yoğunluktaki cisim batabilir, küçük olanı yüzer. Biçim, ortalama yoğunluğu değiştirir.", "Ağır olan her şey batar sanmak, gemiyi açıklayamaz.", ["Yoğunluk kütle bölü hacimdir", "Sıvıdan yoğunu batabilir", "Aynı madde benzer koşullarda benzer yoğunluktadır"], ["Yoğunluk yalnız kütledir", "Buz sudan ağır olduğu için batar", "Hacim yoğunluğu değiştirmez"], yogun)(n),
  "6|Elektriğin iletimi": daily("İletim", "Metaller elektrik akımını iletir, plastik ve kuru tahta iletmez. Islak el ve priz bir araya gelmemelidir. İletken ile yalıtkan güvenlik kararını belirler.", "Her katıyı iletken sanmak plastik teli bakır yerine koydurur.", ["Bakır iletkendir", "Plastik yalıtkandır", "Islak elle prize dokunulmaz"], ["Plastik teli ampul yakar", "Su her zaman yalıtkandır", "İletkenlik renk ile anlaşılır"], ilet),
  "6|Elektriksel direnç": daily("Direnç", "Direnç, iletkenin akıma karşı koyma özelliğidir. Tel uzadıkça ve inceldikçe direnç artabilir. Direnç düşünce aynı pilde ampul daha parlak yanabilir.", "Uzun teli her zaman daha parlak sanmak direnci ters okumaktır.", ["Uzun telin direnci artabilir", "İnce tel daha çok direnç gösterebilir", "Küçük direnç akımı kolaylaştırır"], ["Direnç akımı üretir", "Kalın tel her zaman daha sönük yapar", "Direnç bir kuvvettir"], direnc),
  "6|Biyoçeşitlilik": daily("Çeşitlilik", "Biyoçeşitlilik, bir bölgedeki canlı türlerinin zenginliğidir. Tür azalırsa besin ağı zayıflar. Avlanma, kirlilik ve yaşam alanı kaybı başlıca tehditlerdir.", "Bir türü gereksiz sanmak, onun besin ağındaki yerini siler.", ["Tür çeşitliliği ağı güçlendirir", "Yaşam alanı kaybı türü azaltır", "Korunan alan türü saklar"], ["Her yabancı tür zararsızdır", "Yangın ormanı yeniler, zarar vermez", "Tek tür yeterlidir"], biyo),
  "6|İnsan ve çevre": daily("Çevre", "İnsan tüketimi suyu, toprağı ve havayı etkiler. Tasarruf ve atığı ayırmak bu etkiyi küçültür. Sürdürülebilir tercih, bugünkü işi gelecek kuşağın hakkını yemeden yapmaktır.", "Tek kişinin fark etmeyeceğini sanmak, kalabalık etkiyi yok sayar.", ["Atık ayırmak kaynağı korur", "İsraf gizli bir tüketimdir", "Enerji tasarrufu yakıtı azaltır"], ["Lavabo her yağı temizler", "Poşet toprakta hemen yok olur", "Çevre yalnız devletin işidir"], cevre),
  "6|Yıl sonu tekrarı": daily("Altıncı sınıf fen", "Yıl sonunda tutulma sırası, hız ile sürat, yoğunluk ve iletkenlik yeniden ayrılır. Her ölçüm kendi birimine bağlanır.", "Birimleri birbirinin yerine yazmak sonucu anlamsız kılar.", ["Tutulmada sıra ışık, engel ve gölgedir", "Yoğunluk kütle bölü hacimdir", "Plastik yalıtkandır"], ["Hızın yönü yoktur", "Yoğunluk yalnız hacimdir", "Her metal yalıtkandır"], yil6),
}
