import { pack } from "./fact.js"
import { autoFen } from "./fen-auto.js"
import { upperFen } from "./fen-upper.js"
import { fen78 } from "./fen-78.js"

function L(q, title, teach, watch, example, correct, a, b, c, why) {
  return [title, teach, watch, example, q, correct, a, b, c, why]
}

const FEN = {
  "5|Laboratuvar güvenliği"(n) {
    return pack(n, [
      L("Deney öncesi ilk güvenlik adımı hangisidir?", "Önlük ve kural", "Laboratuvarda deney başlamadan önce öğretmenin kuralı dinlenir ve önlük giyilir. Malzeme, ne işe yaradığı bilinmeden elde dolaştırılmaz.", "Arkadaşın uyarısını şaka saymak kazaya yol açar. Kural, cesareti değil dikkati ister.", "Önlük takılı, saç toplu ve öğretmenin sözü bitmişse deney başlar.", "Öğretmenin yönergesini dinlemek", "Malzemeyi koklamak", "Artan sıvıyı lavaboya dökmek", "Gözlüksüz ateşe eğilmek", "Yönerge bilinmeden deney başlatılmaz."),
      L("Cam malzeme kırılırsa ne yapılır?", "Kırık cam", "Kırılan cam çıplak elle toplanmaz. Öğretmene haber verilir, süpürge ve faraş kullanılır. Kesik olursa yara temizlenir ve haber verilir.", "Kırığı cebine atmak hem keser hem bir sonraki deneyi bozar.", "Beher kırıldıysa parçalar faraşa alınır, yere çıplak el sürülmez.", "Öğretmene söyleyip faraş kullanmak", "Parçaları avuçlamak", "Üstünü ayakkabıyla ezmek", "Çöpe elle tıkmak", "Cam keskin kenar bırakır."),
      L("Gözlüğe ne zaman ihtiyaç vardır?", "Göz koruması", "Sıçrama, ısıtma veya toz çıkan işlerde gözlük takılır. Gözlük, meraktan değil sıvının yüze gelme ihtimalinden takılır.", "Gözlüğü alında taşımak korumaz. Cam, göz hizasındadır.", "Su ısıtılırken gözlük takılıdır; buhar ve sıçrama yüze gelebilir.", "Isıtma ve sıçramada takmak", "Yalnız fotoğraf için", "Deney bitince çıkarmamak şart, takmak değil", "Gözlüğü boyunda bırakmak", "Koruma, riskli adımda gözün önündedir."),
      L("Tadına bakmak neden yasaktır?", "Tatmak yok", "Laboratuvar malzemesinin tadına, kokusuna bakılmaz. Şeker gibi görünen bir toz başka bir kimyasal olabilir. Tanıma işi etiket ve öğretmenle yapılır.", "Evdeki tuzu hatırlatıyor diye parmak ucunu daldırmak zehirlenme riskidir.", "Beyaz tozun adı etikette yazar. Etiket okunmadan madde ağza yaklaştırılmaz.", "Etiketi okuyup ağza yaklaştırmamak", "Azıcık tatmak", "Kokuyu derin çekmek", "Arkadaşa ikram etmek", "Madde, görünüşünden tanınmaz."),
      L("Deney bitince masa nasıl bırakılır?", "Toplamak", "Deney bitince ocak kapatılır, malzeme yerine konur, masa silinir ve eller yıkanır. Düzen, sonraki grubun güvenliğidir.", "Islak masayı öylece bırakmak kaygan zemin ve karışmış kap demektir.", "Bek alevi söndürülür, beher soğuyunca rafa döner, eller sabunla yıkanır.", "Ocağı kapatıp elleri yıkamak", "Alevi açık bırakmak", "Artık sıvıyı cebine koymak", "Etiketleri sökmek", "Kapanış, açılış kadar kuraldır."),
    ], "5 lab")
  },
  "5|Gökyüzündeki komşumuz: Güneş"(n) {
    return pack(n, [
      L("Güneş hangi tür gökcismidir?", "Yıldız", "Güneş, kendi ışığını ve ısısını üreten bir yıldızdır. Gezegenler ve uydular bu ışığı üretemez; ancak yansıtabilir. Gündüz aydınlığı bu yüzden Güneş’ten gelir.", "Güneş’i çok parlak bir gezegen sanmak, ışık kaynağı ile ışığı yansıtan cismi karıştırır.", "Dünya’nın gündüz olan yüzü, Güneş’in gönderdiği ışıkla aydınlanır.", "Kendi ışığını üreten yıldız", "Dünya’nın uydusu", "Soğuk bir gezegen", "Işığını Ay’dan alan cisim", "Yıldız ışık üretir, gezegen yansıtır."),
      L("Güneş sisteminde merkezde ne vardır?", "Merkez", "Güneş sisteminde Güneş merkezdedir. Gezegenler onun çevresindeki yörüngelerde dolanır. Bu düzenin ısı ve ışık kaynağı da Güneş’tir.", "Ay’ı merkeze koymak, uyduyu yıldızın yerine geçirmektir. Ay, Dünya’nın çevresindedir.", "Dünya, Güneş’in çevresinde dolanırken Ay da Dünya’nın çevresinde dolanır.", "Güneş", "Ay", "Dünya’nın merkezi", "Kutup yıldızı zorunlu olarak", "Merkezdeki cisim, sistemin yıldızıdır."),
      L("Güneş’e neden çıplak gözle bakılmaz?", "Göz güvenliği", "Güneş’e çıplak gözle, dürbünle veya sıradan güneş gözlüğüyle bakılmaz. Işık gözün ağ tabakasını yakabilir. Gözlem, öğretmenin verdiği güvenli yöntemle ve kısa süre yapılır.", "Tutulma var diye doğrudan bakmak tehlikeyi azaltmaz. Özel filtre yoksa bakılmaz.", "Gündüz gökyüzüne not alırken yüz Güneş’e çevrilmez; gölge ve saat kullanılır.", "Çıplak gözle bakılmaz", "Öğle vakti kısa bakılır", "Dürbünle bakmak güvenlidir", "Sıradan gözlük yeter", "Güneş ışığı göze doğrudan zarar verir."),
      L("Güneş neden küçük görünür?", "Uzaklık", "Güneş, Dünya’dan çok büyüktür. Küçük görünmesinin nedeni uzak olmasıdır. Uzak bir uçak da büyük olduğu halde nokta gibi görünür.", "Küçük göründüğü için Güneş’i Ay’dan küçük sanmak göz yanılgısıdır.", "Bir topu gözden uzaklaştırdıkça daha küçük görünür; Güneş de uzakta olduğu için küçük görünür.", "Çok uzak olduğu için", "Gerçekten Ay’dan küçük olduğu için", "Işık zayıf olduğu için", "Gezegen olduğu için", "Görünen büyüklük, uzaklıktan etkilenir."),
      L("Güneş Dünya’ya ne gönderir?", "Işık ve ısı", "Güneş Dünya’ya ışık ve ısı gönderir. Bitkiler bu ışıkla besin üretir, hava ve su ısınır. Güneş olmasaydı bildiğimiz gündüz de olmazdı.", "Güneş’in yalnız süs ışığı verdiğini sanmak ısısını yok sayar.", "Çamaşırlar Güneş’te kurur çünkü hem ışık hem ısı gelir.", "Işık ve ısı", "Yalnız ses", "Yalnız rüzgâr", "Soğuk hava", "Yıldızın Dünya’ya ulaşan etkisi ışık ve ısıdır."),
      L("Gündüz nasıl oluşur?", "Gündüz", "Dünya’nın Güneş’e dönük yüzü gündüz, öteki yüzü gece yaşar. Gündüz, Güneş’in o yüzü aydınlatmasıdır. Güneş’in her sabah ‘yeniden doğması’ bir görünüştür.", "Gündüzü Güneş’in Dünya’nın içinden geçmesi sanmak modeli bozar.", "Sınıfın perdeyle kapanan tarafı kararır, açık taraf aydınlanır. Gezegenin aydınlanan yüzü de gündüzdür.", "Güneş’e bakan yüzün aydınlanması", "Ay’ın Güneş’i kapatması", "Yıldızların sönmesi", "Bulutun ısıtması", "Aydınlanan yarımküre gündüzü yaşar."),
      L("Gölge Güneş’in yerini nasıl ele verir?", "Gölge", "Saydam olmayan bir cisim ışığı kesince gölge oluşur. Gölge, ışığın geldiği yönün tersine düşer. Güneş yüksekteyken gölgeler kısalır.", "Gölgeyi Güneş’in önüne, ışıkla aynı yöne düşürmek yönü ters alır.", "Sabah uzun olan gölge, öğleyin kısalır. Bu, Güneş’in gökyüzündeki yüksekliğinin değiştiğini gösterir.", "Işığın ters yönüne", "Her zaman Güneş’in üstüne", "Yalnız gece", "Saydam camda koyu bir leke olarak zorunlu", "Işık gelmeyen tarafta gölge vardır."),
      L("Güneş enerjisi günlük hayatta nerede kullanılır?", "Güneş enerjisi", "Güneş’ten gelen enerji su ısıtabilir, güneş paneliyle elektrik üretimine katkı verebilir ve çamaşırı kurutur. Kaynak, yakıt taşımadan gökyüzünden gelir.", "Paneli gece de aynı güçte sanmak, ışık olmayınca üretimin düşeceğini unutmaktır.", "Çatıdaki panel gündüz Güneş ışığını elektriğe çevirir. Gece bu iş için depolanmış enerji gerekir.", "Işığı ve ısıyı işe çevirmek", "Ay ışığını yakıt yapmak", "Gölgeyi yakmak", "Yağmuru panelde depolamak", "Panel, gelen ışık varken çalışır."),
      L("Yıldız, gezegen ve uydu nasıl ayrılır?", "Üç cisim", "Yıldız kendi ışığını üretir. Gezegen, yıldızın çevresinde dolanır ve ışığı yansıtır. Uydu, bir gezegenin çevresinde dolanır. Ay, Dünya’nın uydusudur.", "Ay’ı yıldız saymak, gece parlak görünmesini ışık üretmek sanmaktır.", "Güneş yıldız, Dünya gezegen, Ay uydudur. Üçünün görevi birbirinin yerine geçmez.", "Güneş yıldız, Ay uydudur", "Üçü de yıldızdır", "Ay gezegen, Güneş uydudur", "Dünya yıldızdır", "Işık üretmek yalnız yıldıza aittir."),
      L("Güneş gözlemi hangi yolla güvenlidir?", "Güvenli gözlem", "Güneş’in yeri, gökyüzüne bakmadan da izlenebilir: gölgenin boyu, ısınan yüzey ve öğretmenin gösterdiği güvenli düzenek. Doğrudan bakmak bilgiyi artırmaz, gözü yakar.", "Daha çok bilgi için dürbünü Güneş’e çevirmek tehlikeyi büyütür.", "Bahçedeki çubuğun gölgesi öğlene doğru kısalıyorsa Güneş yükselmiştir. Bunu görmek için Güneş’e bakılmaz.", "Gölgeden ve güvenli düzenekten", "Dürbünü Güneş’e tutarak", "Öğle güneşine uzun bakarak", "Aynayla göze yansıtarak", "Gözlem, ışığı göze toplamadan da yapılır."),
    ], "5 güneş")
  },
}

export function fenLesson(grade, title, dayCount) {
  const build = FEN[`${grade}|${title}`] || autoFen[`${grade}|${title}`] || upperFen[`${grade}|${title}`] || fen78[`${grade}|${title}`]
  if (!build) throw new Error(`Fen eksik: ${grade}. sınıf ${title}`)
  return build(dayCount)
}
